on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    
    - uses: azure/docker-login@v1
      with:
        login-server: deploymenttapaswi.azurecr.io
        username: ${{ secrets.acr_deploymenttapaswi_username }}
        password: ${{ secrets.acr_deploymenttapaswi_password }}
    
    - name: Build and push image to ACR
      id: build-image
      run: |
        docker build "$GITHUB_WORKSPACE/" -f  "Dockerfile" -t deploymenttapaswi.azurecr.io/deployment:${{ github.sha }} --label dockerfile-path=Dockerfile
        docker push deploymenttapaswi.azurecr.io/deployment:${{ github.sha }}
    
    - uses: azure/k8s-set-context@v1
      with:
         kubeconfig: ${{ secrets.aks_deployment_kubeConfig }}
      id: login
    
    - name: Create namespace
      run: |
        namespacePresent=`kubectl get namespace | grep default | wc -l`
        if [ $namespacePresent -eq 0 ]
        then
            echo `kubectl create namespace default`
        fi

    - uses: azure/k8s-create-secret@v1
      with:
        namespace: default
        container-registry-url: deploymenttapaswi.azurecr.io
        container-registry-username: ${{ secrets.acr_deploymenttapaswi_username }}
        container-registry-password: ${{ secrets.acr_deploymenttapaswi_password }}
        secret-name: deploymentdockerauth
       
    - uses: azure/k8s-bake@v1
      with:
        renderEngine: 'helm'
        helmChart: helm
        releaseName: 'aks-helm-release'
        helm-version: 'latest' 
        silent: 'false'
        overrideFiles: |
          
        overrides: |
          replicas:2
          image.repository:deploymenttapaswi.azurecr.io/deployment
          image.tag:${{ github.sha }}
          imagePullSecrets:
            -name:deploymentdockerauth
      id: bake

    - uses: azure/k8s-deploy@v1.2
      with:
        namespace: default
        manifests: ${{ steps.bake.outputs.manifestsBundle }}
        images: |
          deploymenttapaswi.azurecr.io/deployment:${{ github.sha }}
        imagepullsecrets: |
          deploymentdockerauth
